server:
  port: 10000
spring:
  application:
    name: websocket-redis-subscribe
  redis:
    host: 47.99.73.234
    port: 16379
    timeout: 20000
    jedis:
      pool:
        max-active: -1
        max-idle: 50
        max-wait: 500
        min-idle: 1